"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 13:41:11.999147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('auth_uid', sa.String(length=128), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_uid')
    )
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('arm_span_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('wrist_cm', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('checkins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('soreness', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('max_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('tested_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('max_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_max_tests_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sets', sa.JSON(), nullable=False),
    sa.Column('policy', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('readiness', sa.Float(), nullable=False),
    sa.Column('max_reps', sa.Integer(), nullable=False),
    sa.Column('load', sa.Float(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'exercise')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=32), nullable=False),
    sa.Column('training_months', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('wake_time', sa.String(length=5), nullable=False),
    sa.Column('window_start', sa.String(length=5), nullable=False),
    sa.Column('window_end', sa.String(length=5), nullable=False),
    sa.Column('quiet_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_end', sa.String(length=5), nullable=False),
    sa.Column('prompt_limit', sa.Integer(), nullable=False),
    sa.Column('screening_flags', sa.JSON(), nullable=False),
    sa.Column('clearance_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('set_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=False),
    sa.Column('set_ref', sa.String(length=8), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('done_reps', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.create_index('ix_set_logs_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_logs_user_id'))
        batch_op.drop_index('ix_set_logs_user_date')

    op.drop_table('set_logs')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))

    op.drop_table('plans')
    with op.batch_alter_table('max_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_max_tests_user_id'))

    op.drop_table('max_tests')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))

    op.drop_table('consents')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_user_id'))

    op.drop_table('checkins')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_user_id'))

    op.drop_table('body_measurements')
    op.drop_table('users')
    # ### end Alembic commands ###
