"""weekly progression

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04 15:10:40.121671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('exercise', sa.String(length=32), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('extra_sets', sa.Integer(), nullable=False),
    sa.Column('extra_reps', sa.Integer(), nullable=False),
    sa.Column('last_step', sa.String(length=8), nullable=True),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise', 'week_start')
    )
    with op.batch_alter_table('progressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progressions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progressions_user_id'))

    op.drop_table('progressions')
    # ### end Alembic commands ###
