"""session mode

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-04 21:59:28.967298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ladder', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('below_range', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('last_rating', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ladder')
    )
    with op.batch_alter_table('exercise_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_states_user_id'), ['user_id'], unique=False)

    op.create_table('session_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('template', sa.String(length=16), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('volume_step', sa.Integer(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('soreness', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('readiness', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('quit_reason', sa.String(length=16), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date')
    )
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_plans_user_id'), ['user_id'], unique=False)

    op.create_table('session_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('volume_step', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start')
    )
    with op.batch_alter_table('session_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('session_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('available', sa.JSON(), nullable=False),
    sa.Column('high_impact', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('session_set_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ladder', sa.String(length=16), nullable=False),
    sa.Column('exercise_key', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('effort', sa.String(length=8), nullable=False),
    sa.Column('tested', sa.Boolean(), nullable=False),
    sa.Column('pain', sa.Boolean(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_set_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_set_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_session_set_logs_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_set_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_set_logs_user_id'))
        batch_op.drop_index('ix_session_set_logs_user_date')
        batch_op.drop_index(batch_op.f('ix_session_set_logs_session_id'))

    op.drop_table('session_set_logs')
    op.drop_table('session_settings')
    with op.batch_alter_table('session_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_reviews_user_id'))

    op.drop_table('session_reviews')
    with op.batch_alter_table('session_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_plans_user_id'))

    op.drop_table('session_plans')
    with op.batch_alter_table('exercise_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_states_user_id'))

    op.drop_table('exercise_states')
    # ### end Alembic commands ###
